export enum PlatformsEnum {
  NETFLIX = 'NETFLIX',
  HBO_MAX = 'HBO_MAX',
  YOUTUBE_PREMIUM = 'YOUTUBE_PREMIUM',
  SPOTIFY = 'SPOTIFY',
  AMAZON_PRIME = 'AMAZON_PRIME',
  MOVISTAR_PLAY = 'MOVISTAR_PLAY',
  DIRECTV_GO = 'DIRECTV_GO',
  DISNEY_PLUS = 'DISNEY_PLUS',
  STAR_PLUS = 'STAR_PLUS',
  MOVISTAR_POSTPAGO = 'MOVISTAR_POSTPAGO',
  MOVISTAR_PREPAGO = 'MOVISTAR_PREPAGO',
  CLARO_POSTPAGO = 'CLARO_POSTPAGO',
  CLARO_PREPAGO = 'CLARO_PREPAGO',
}

export enum PlatformLogo {
  'NETFLIX' = 'https://asset.brandfetch.io/ideQwN5lBE/idEpcd_1YX.jpeg',
  'HBO_MAX' = 'https://asset.brandfetch.io/idKKo6p4ks/iddpv1U5qe.jpeg',
  'YOUTUBE_PREMIUM' = 'https://asset.brandfetch.io/idVfYwcuQz/idmfkl4meA.jpeg',
  'SPOTIFY' = 'https://asset.brandfetch.io/id20mQyGeY/idDziqAPQj.jpeg',
  'AMAZON_PRIME' = 'https://asset.brandfetch.io/idXRXV6qi8/id5v14EFo4.png',
  'MOVISTAR_PLAY' = 'https://asset.brandfetch.io/idMGdiCdTB/idcFf9dYmW.jpeg',
  'DIRECTV_GO' = 'https://asset.brandfetch.io/id8aYBg8Hz/idS-l74Kph.jpeg',
  'DISNEY_PLUS' = 'https://asset.brandfetch.io/idhQlYRiX2/idRXC5mxqs.png',
  'STAR_PLUS' = 'https://yt3.ggpht.com/5lH4708bpazbm9qQQ6AOXw3_8DhAossUCxwxP2_bARGE4lbAikY0tgosLbviarcvxdFAi34OgQ=s900-c-k-c0x00ffffff-no-rj',
  'MOVISTAR_POSTPAGO' = 'https://asset.brandfetch.io/idEVTEgG6j/idQspcBYeB.jpeg',
  'MOVISTAR_PREPAGO' = 'https://asset.brandfetch.io/idEVTEgG6j/idQspcBYeB.jpeg',
  'CLARO_POSTPAGO' = 'https://play-lh.googleusercontent.com/P8kJgr1Zb_e2QOPR5GO6mv4x1tH5EPdYso0eSpKlF9ix14ez_RL2uECcxG9JKM8eFD0',
  'CLARO_PREPAGO' = 'https://play-lh.googleusercontent.com/P8kJgr1Zb_e2QOPR5GO6mv4x1tH5EPdYso0eSpKlF9ix14ez_RL2uECcxG9JKM8eFD0',
}
